# io config
entsoe_token: 
google_api_key: 
opsd_vres_base_year: 2016

#matching config
# add a pandas query statement after the source name to filter the sources individually, e.g. - Carma: Fueltype=='Natural Gas'
# see http://pandas.pydata.org/pandas-docs/stable/indexing.html#the-query-method for info about query syntax
matching_sources:
    - CARMA
    - ENTSOE
    - ESE
    - GEO
    - GPD
    - IWPDCY
    - OPSD
    # - WEPP

fully_included_sources:
    - OPSD
    - ESE: Country not in ['Switzerland']
    - ENTSOE: Country not in ['Spain', 'Switzerland']
    - CARMA: Country == 'France' and Fueltype == 'Hydro'
    # - IWPDCY: lat == lat and Country == 'Sweden'

parallel_duke_processes: true
process_limit: 2

#data config
display_net_caps: true
remove_missing_coords: true
target_columns:
    - Name
    - Fueltype
    - Technology
    - Set
    - Country
    - Capacity
#    - Efficiency
    - Duration
    - YearCommissioned
    - Retrofit
    - lat
    - lon
    - File
    - projectID
target_countries:
    - Austria
    - Belgium
    - Bulgaria
    - Croatia
    - Czech Republic
    - Denmark
    - Estonia
    - Finland
    - France
    - Germany
    - Greece
    - Hungary
    - Ireland
    - Italy
    - Latvia
    - Lithuania
    - Luxembourg
    - Netherlands
    - Norway
    - Poland
    - Portugal
    - Romania
    - Slovakia
    - Slovenia
    - Spain
    - Sweden
    - Switzerland
    - United Kingdom
target_fueltypes:
    - Bioenergy
    - Geothermal
    - Hard Coal
    - Hydro
    - Lignite
    - Natural Gas
    - Nuclear
    - Oil
    - Other
    - Solar
    - Waste
    - Wind
target_sets:
    - CHP
    - PP
    - Stores
target_technologies:
    - CCGT
    - OCGT
    - Steam Turbine
    - Combustion Engine
    - Run-Of-River
    - Pumped Storage
    - Reservoir
    - Marine
    - Onshore
    - Offshore
    - PV
    - CSP

# Allowed countries for matches of only CARMA and GEO
CARMA_GEO_countries:
    -  Austria
    -  Belgium
    -  Bulgaria
    -  Croatia
    -  Denmark
    -  Estonia
    -  France
    -  Germany
    -  Ireland
    -  Italy
    -  Luxembourg
    -  Netherlands
    -  Romania
    -  Slovakia
    -  Sweden
    
# heuristic config
fuel_to_lifetime:
    Bioenergy: 20
    Geothermal: 15
    Hard Coal: 45
    Hydro: 100
    Lignite: 45
    Natural Gas: 40
    Nuclear: 50
    Oil: 40
    Other: 5
    Solar: 25
    Waste: 25
    Wind: 25

# plotting config
fuel_to_color:
    OCGT: darkorange
    Hydro: royalblue
    Run-of-river: navy
    Ror: navy
    Lignite: orangered
    Nuclear: yellow
    Solar: gold
    Windoff: cornflowerblue
    Windon: steelblue
    Offshore: cornflowerblue
    Onshore: steelblue
    Wind: steelblue
    Bioenergy: g
    Natural Gas: firebrick
    CCGT: firebrick
    Coal: k
    Hard Coal: dimgray
    Oil: darkgreen
    Other: silver
    Waste: grey
    Geothermal: orange
    Battery: purple
    Hydrogen Storage: teal
    Electro-mechanical: teal
    Total: gold
